from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from ..db import get_db
from ..models import Ticket, ActivityLog
from ..services.log_service import log_action
from ..services.ai_service import summarize_ticket, generate_reply
import uuid

router = APIRouter()


@router.post("/tickets")
def create_ticket(
    title: str,
    description: str = "",
    name: str = "",
    email: str = "",
    db: Session = Depends(get_db)
):
    new_ticket = Ticket(
        title=title,
        description=description,
        name=name if name else None,
        email=email if email else None
    )

    db.add(new_ticket)
    db.commit()
    log_action(db, new_ticket.id, "Ticket created")

    db.refresh(new_ticket)

    return {
        "id": str(new_ticket.id),
        "title": new_ticket.title,
        "status": new_ticket.status
    }


@router.get("/tickets/recent")
def recent_tickets(db: Session = Depends(get_db)):
    """Get most recently created tickets"""
    tickets = db.query(Ticket)\
        .order_by(Ticket.created_at.desc())\
        .limit(4)\
        .all()

    return tickets


@router.get("/tickets")
def get_tickets(db: Session = Depends(get_db)):
    """Get all tickets (for admin view)"""
    tickets = db.query(Ticket).all()
    return tickets


@router.get("/tickets/{ticket_id}")
def get_ticket(ticket_id: str, db: Session = Depends(get_db)):
    """Get a single ticket by ID"""
    ticket = db.query(Ticket).filter(Ticket.id == ticket_id).first()
    return ticket


@router.put("/tickets/{ticket_id}")
def update_ticket(
    ticket_id: str,
    title: str,
    description: str,
    db: Session = Depends(get_db)
):
    """Update ticket title and description"""
    ticket = db.query(Ticket).filter(Ticket.id == ticket_id).first()

    if not ticket:
        return {"error": "not found"}

    ticket.title = title
    ticket.description = description

    db.commit()
    db.refresh(ticket)

    return ticket


@router.delete("/tickets/{ticket_id}")
def delete_ticket(ticket_id: str, db: Session = Depends(get_db)):
    """Delete a ticket by ID"""
    ticket = db.query(Ticket).filter(Ticket.id == uuid.UUID(ticket_id)).first()

    if not ticket:
        return {"error": "not found"}

    db.delete(ticket)
    db.commit()

    return {"msg": "deleted"}


@router.put("/tickets/{ticket_id}/status")
def update_status(
    ticket_id: str,
    status: str,
    db: Session = Depends(get_db)
):
    """Update ticket status (e.g., OPEN, IN_PROGRESS, DONE)"""
    ticket = db.query(Ticket).filter(Ticket.id == uuid.UUID(ticket_id)).first()

    if not ticket:
        return {"error": "not found"}

    ticket.status = status
    db.commit()
    log_action(db, ticket.id, f"Status changed to {status}")

    db.refresh(ticket)

    return {"msg": "updated", "status": ticket.status}


@router.post("/tickets/{ticket_id}/summarize")
def summarize_ticket_endpoint(ticket_id: str, db: Session = Depends(get_db)):
    """Generate AI summary based on the ticket content"""
    return summarize_ticket(ticket_id, db)


@router.post("/tickets/{ticket_id}/reply")
def generate_reply_endpoint(ticket_id: str, db: Session = Depends(get_db)):
    """Reply generated by AI based on the ticket content"""
    return generate_reply(ticket_id, db)


@router.get("/tickets/{ticket_id}/logs")
def get_logs(ticket_id: str, db: Session = Depends(get_db)):
    """Get activity logs for a specific ticket"""
    logs = db.query(ActivityLog)\
        .filter(ActivityLog.ticket_id == uuid.UUID(ticket_id))\
        .order_by(ActivityLog.timestamp.desc())\
        .all()

    return logs

